POST http://localhost:3000/api/auth/admin/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "123456"
}

###

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "email": "user@gmail.com",
    "password": "123456"
}

###
GET http://localhost:3000/api/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjMyNTAxMjlmZTA0NzJkMDJiNDE0N2QiLCJpYXQiOjE3MTQ2MzkzMTEsImV4cCI6MTcxNDYzOTMyNn0.pB9fErU8jn7_2ORjAreBeJV8YYIC5sy9PGFz5ueEDdA
###

GET http://localhost:3000/api/token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjMyNTAxMjlmZTA0NzJkMDJiNDE0N2QiLCJpYXQiOjE3MTQ2MzkyODcsImV4cCI6MTcxNDcyNTY4N30.jGt5McDCeZUaZ96vfoxpKC3Uz7bYUwqNWpxg1lLb9h8"
}

###

PATCH  http://localhost:3000/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjMyNTAxMjlmZTA0NzJkMDJiNDE0N2QiLCJpYXQiOjE3MTQ2Mzk1NjksImV4cCI6MTcxNDYzOTU4NH0.k1H0FtzxkwN42TFzbdkxjjAM9IJsglVZnlbEDB8Tz0c

###

PATCH  http://localhost:3000/api/auth/admin/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjM1ZjczOGQzZTBhOTU4YjQxMWYyZWEiLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNzE0ODE3NjgzLCJleHAiOjE3MTQ5MDQwODN9.NK3Zg-QdNGPRMD-auJnjKB5FMpd9lzzgw65u13lulWE


###

GET http://localhost:3000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjMzOTI2ZmEwZmFiN2I3NmU2ODhjZjgiLCJpYXQiOjE3MTQ2NTU4OTQsImV4cCI6MTcxNDc0MjI5NH0.tLAmhpgop_GuFgKiAQ0jh3PzKhhvXg3K-Wf2fJxQGtI

###
PATCH http://localhost:3000/api/categories/66390c1a771b3fb4097f53dd
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjM1ZjczOGQzZTBhOTU4YjQxMWYyZWEiLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNzE1MDY3MDMyLCJleHAiOjE3MTUxNTM0MzJ9.zddmuOoaL8se7k9AeH_Z1kB74wZjOxIxgjBaDEyvp5Y
Content-Type: application/json

{
    "active": true
}

###
DELETE http://localhost:3000/api/categories/adwda
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjNhZjExNjUxM2QyMmU1ZjE3MGQwYWQiLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNzE1MTUzOTQ1LCJleHAiOjE3MTUyNDAzNDV9.rgCYh_Cg-sNR93wcvLiAZiEs2spHbkesfRI9n2sf23M
