POST http://localhost:3000/api/auth/admin/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "123456"
}

###

POST http://localhost:3000/api/brands
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjNhZjExNjUxM2QyMmU1ZjE3MGQwYWQiLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNzE1MjM0NzMxLCJleHAiOjE3MTUzMjExMzF9.7Ms_ebAkVSjnxEZ59OrHBClb9j72ekg1awF_vbPln2U
Content-Type: application/json

{
    "name": "Brand 3",
    "description": "Brand description"
}

###
DELETE   http://localhost:3000/api/brands/663c68c1dec58b3a5543da71
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjNhZjExNjUxM2QyMmU1ZjE3MGQwYWQiLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNzE1MjM0NzMxLCJleHAiOjE3MTUzMjExMzF9.7Ms_ebAkVSjnxEZ59OrHBClb9j72ekg1awF_vbPln2U
Content-Type: application/json

{
    "name": "New Brand",
    "description": "123",
    "active": true
}